# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q pipenv flake8 codecov
        pipenv sync --dev
        cp contrib/env-sample .env
    - name: rodar flake8
      uses: py-actions/flake8@v1
      with:
        checkName: 'flake8_py3'
    - name: Test with pytest
      run: |
        pipenv run pytest --cov=curso-django
    - name: Relatório Coverage
      run: |
        pipenv run codecov
